### PR TITLE
Small optimisations

### LINKED ISSUE #45: Simplify h_evals loop in verifier
```rust
let (_, h_eval) = self
            .h_evals
            .iter()
            .fold((C::Scalar::one(), C::Scalar::zero()), |(cur, acc), eval| {
                (cur * &x_3n, acc + &(cur * eval))
            });
```

Rewriting x^n as x, we can apply Horner's rule to simplify

```rust
let h_eval = self
            .h_evals
            .iter()
            .rev()
            .fold(C::Scalar::zero(), |acc, eval| {
                acc * &x_3n + eval
            });
```

### PR DESCRIPTION
**Pull request by str4d**
Closes #45

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

**Comment by daira** [comment]
re-utACK

**Comment by therealyingtong** [comment]
Force-pushed to rebase on ColumnType changes.

**Review by therealyingtong — APPROVED** [review]
ACK

**Pull request merged**
