### PR TITLE
Improved error handling

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by daira — COMMENTED** [review]
ukACK so far.

**Review by therealyingtong — APPROVED** [review]
utACK modulo intra-doc links

**Review by therealyingtong — APPROVED** [review]
utACK

**Comment by str4d** [comment]
[Rebased on main](https://github.com/zcash/halo2/compare/f7def753f9a2c44ee62c3a5c455f105608c170d8..9f0d6e2db69eeb03318161db3eb0db93557036e5) to fix merge conflict. I also updated the book to document the required Debian packages for the `dev-graph` feature (which I just discovered, trying to use it on a fresh installation).

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/halo2/compare/9f0d6e2db69eeb03318161db3eb0db93557036e5..a222cdc6d4b327d0d28e16fea6a37dd439d9eaaf) to fix

**Pull request merged**
