### PR TITLE
Add harness for `nightly -> beta -> stable` dev workflow

### PR DESCRIPTION
**Pull request by str4d**
Part of zcash/halo2#707.

### CODE REVIEW

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/halo2/compare/8e84f4953b34eda92dc0660117381a672f6100ed..4b804a141ab2e912fa3be8c11d1161e55b0e5b99) to tweak CI naming for clarity, and migrated the SHA-256 gadget and chip to `nightly` as the first example of usage.

**Review by CPerezz — APPROVED** [review]
LGTM! 
@han0110 @killic would you like to check this too??

**Comment by ebfull** [comment]
I'm ACK on this approach.

**Review by ebfull — APPROVED** [review]

**Review by ed255 — APPROVED** [review]
LGTM!

**Pull request merged**
